[package]
name = "tarnisheds-arsenal-desktop"
version = "0.14.1"
description = "Tarnished's Arsenal desktop app"
authors = ["Tarnished's Arsenal contributors"]
license = "MIT"
repository = ""
edition = "2024"
default-run = "tarnisheds-arsenal-desktop"

[profile.release]
lto = "thin"
codegen-units = 1

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
er_optimizer_core = { path = "../../../core/er_optimizer_core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
